# Generated by Django 3.1.6 on 2021-03-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(max_length=255)),
                ("merchent", models.CharField(max_length=255)),
                ("decreption", models.CharField(blank=True, max_length=255, null=True)),
                ("categroy", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("updated_created", models.DateTimeField(auto_now=True)),
            ],
        )
    ]
